version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            docker build -t eyenx/drone-build-trigger . 
      - run:
          name: Push Image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin && docker tag eyenx/drone-build-trigger:latest eyenx/drone-build-trigger:$CIRCLE_SHA1 && docker push eyenx/drone-build-trigger:latest && docker push eyenx/drone-build-trigger:$CIRCLE_SHA1
